@startuml
skinparam componentStyle uml2

actor Alisa as Alisa
actor Marusia as Marusia

package "Assistant service" as Assist {
    component "[Nginx]" as Nginx <<Web>>
    component "[FastAPI]" as AssistApi <<Assistant API>>

    component "[Rasa NLU]" as NLUApi <<Intent parse>>
    database "[Redis]" as Redis <<Storage>>

    Nginx -> AssistApi
    AssistApi --> NLUApi : Выделение намерений \n из запроса
    Redis <- AssistApi : Кэш запросов в \n"[Rasa NLU]" и AsyncAPI
}

package AsyncAPI {
}

AssistApi --> AsyncAPI : Поиск информации \nо фильме
Nginx <-- Alisa
Nginx <- Marusia

@enduml
