name: main

on:
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Submodule Checkout
        # You may pin to the exact commit or the version.
        # uses: jwsi/submodule-checkout@428791ee676835d4c6cb9998b38977c5c89fba46
        uses: jwsi/submodule-checkout@v1
        with:
          # SSH private key for private submodule access
          ssh-key: |
             '${{ secrets.SUBMODULE_ASYNCAPI }}'
