name: main

on:
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: erpheus/private-submodule-checkout@v1
        with:
          deployment_key: ${{ secrets.SUBMODULE_ASYNCAPI }}

