name: tests

on:
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
           ssh-key: |
             ${{ secrets.SUBMODULE_ASYNCAPI }}
           submodules: 'recursive'
      - name: Test
        run: git submodule update --init && docker-compose -f assistant/src/tests/functional/docker-compose.yml up --build tests
