name: tests

on:
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Add SSH private keys for submodule repositories
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: |
            ${{ secrets.SUBMODULE_ASYNCAPI }}
            ${{ secrets.SUBMODULE_ETL_MOVIES }}
      - run: git submodule update --init --recursive --remote
      
      - name: Test
        run: git submodule update --init && docker-compose -f assistant/src/tests/functional/docker-compose.yml up --build tests
